name: Create an Issue

on:
  workflow_dispatch:
    inputs:
      issueTitle:
        description: 'Issue Title'
        required: true
      issueBody:
        description: 'Issue Body'
        required: true

jobs:
  create_issue:
    runs-on: ubuntu-latest
    name: Add an Issue to the Repo
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create an Issue
        run: gh issue create --title "${{ inputs.issueTitle }}" --body "${{ inputs.issueBody }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
