name: Print to Logs 3

on:
  workflow_dispatch:

jobs:
  print_something:
    runs-on: ubuntu-latest
    name: Print Something
    steps: 
      - name: Print Something
        shell: bash
        run: | 
          echo "Printing something cool."
          echo "Secret will be masked:"
          echo ${{ secrets.TEST_SECRET }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
