name: PR Comment 2

on:
  pull_request_target:

jobs:
  comment_pr:
    runs-on: ubuntu-latest
    name: Comment on the PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: First Comment on PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            You created a PR! ! :lady_beetle:
            
      - name: Second Comment on PR
        run: gh pr comment $PR_URL --body "Is it ready to merge? Double check! :monocle_face:"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
